# Picks set from sets:
# Each set chooses the suitable hand set, gesture set, network set and mapping set
using_set: main_set

sets:
  main_set:
    gestures: main_set
    hand_mode_sets: set0
    mapping_sets: main_map
    network_set: main_set
  set_1_static:
    gestures: set_1_static
    hand_mode_sets: set0
    mapping_sets: set_1_static
    network_set: set_1_static
  main_set_static:
    gestures: main_set_static
    hand_mode_sets: setl
    mapping_sets: main_set_static
    network_set: main_set
  new_gesture_set:
    gestures: new_gesture_set
    network_set: new_gesture_set

min_confidence: 0.3
since_frame_time: 0.5
touch_turn_on_dist: [0.9, 0.9, 0.9, 0.9,  0.9, 0.9, 0.9]
touch_turn_off_dist: [0.5, 0.5, 0.5, 0.5,  0.5, 0.5, 0.5]
oc_turn_on_thre: [0.94, 0.8, 0.8, 0.8, 0.8]
oc_turn_off_thre: [0.85, 0.6, 0.6, 0.6, 0.6]

# Link to networks in google drive folder
networks_drive_url: https://drive.google.com/drive/folders/1T8jqeyb10WrwnqQoMA25bRKQQvTacF6Y


# This is default network loaded from computer, it can be changed later in UI
network_sets:
  main_set:
    # PyMC3, PyTorch, DTW, deterministic
    static_detection_approach: PyMC3
    dynamic_detection_approach: DTW
    static_network_file: PyMC3-main-set-3.pkl #
    dynamic_network_file: promp
  set_1_static:
    static_detection_approach: PyMC3
    dynamic_detection_approach: PyTorch
    static_network_file: network0.pkl
    dynamic_network_file:
  new_gesture_set:
    static_detection_approach: PyMC3
    dynamic_detection_approach: DTW
    static_network_file: new_network.pkl #
    dynamic_network_file: promp

misc_network_args:
  time_samples: 5

misc:
  rate: 10
  relevant_time: 0.5

hand_mode_sets:
  set0:
    l: static
    r: dynamic
  setl:
    l: static
    r: none
  setbothstatic:
    l: static
    r: static
  setnone:
    l: none
    r: none
## Default option is now at: settings.py

# Mapping gesture ID to MotionPrimitiveID
# Mapping example:
# gestureID: MotionPrimitiveID
mapping_sets:
  main_map:
    grab: gripper
    pinch: gripper
    point: focus
    two: focus
    three: focus
    four: nothing
    five: nothing
    thumbsup: gripper
    swipe_down: touch
    swipe_front_right: kick
    swipe_left: nothing
    swipe_up: go_to_home
    round: touch
    no_gesture: nothing
    # write about
    # solve RLBench task, push buttons in an order
  set0:
    grab: touch
    kick: kick
    nothing: nothing
    pinch: gripper
    victory: go_to_home
  set_1_static:
    grab: nothing
    pinch: nothing
    point: nothing
    respectful: nothing
    victory: nothing
    spock: nothing
    rock: nothing
  main_set_static:
    grab: nothing
    pinch: gripper
    point: nothing
    two: direction_move
    three: nothing
    four: nothing
    five: nothing
    thumbsup: nothing


  new_gesture_set:
    closed_hand: gripper
    opened_hand: gripper
    swipe_down: touch
    swipe_front_right: kick


















#
